# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe5b4adfd9e68bde767b2398246a917bc6ca7c33be1424e69bdc6ea0f6b872328996072f2172a429db7c725fde534562c32d13ce6e2cac582bda6de8a2319162

test:
  secret_key_base: 02be92459fdf702909ffd9ac32adf5daf57b8c1fa0c040cd39eef7491a0057b7f71721a4164be74a052b27673436b8ecdafff9ba3d9e3b6cb98d8e475e875e0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
