# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70d874ff98972b730109306b780262d48d8e499b9a9ed6b004a9a8a77c10566575256d61d5768fb04e734b4be24803d7287058965b67fe86110ada9822ee04fb

test:
  secret_key_base: 42289816ce449b501dc714dd6f184ad87d9085a56ac526619cf01780b2feb82ba92b8e1fc0cbe5e7b7044710568542a9ae29ce6931b282605a0ac6db1bb600c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
