# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a962a7d2e932c1d1f36725d7b51c035b60a679c95aa789b223215cebbea42c1c1e9c5834de274fb61329136f5e6bd264cb946ecb590cc0df7eac528c0f0a78f9

test:
  secret_key_base: 5dfed2675fb86701392dd6202dffe18b69849c877d7fca905d417fe999ca9b75487e993bb42a59e31405d2ac4062c58bc6e4f534e87a4bbcb66a9732b23eb118

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
